--
-- Created by IntelliJ IDEA.
-- User: larsurban
-- Date: 23.01.14
-- Time: 19:19
--


function OnFirstFrame()

    xac_gear_handle_status = dref.getDataref("sim/cockpit/switches/gear_handle_status")
    xac_gpu_av = dref.getDataref("sim/custom/xap/elec/gpu_av")
    xac_gpu_run = dref.getDataref("sim/custom/xap/elec/gpu_run")
    xac_gpu_here = dref.getDataref("sim/custom/xap/elec/gpu_here")
    xac_gpu_on = dref.getDataref("sim/custom/xap/elec/gpu_on")
    xac_bat1_on = dref.getDataref("sim/custom/xap/elec/bat1_on")
    xac_bat2_on = dref.getDataref("sim/custom/xap/elec/bat2_on")
    xac_apu_firetest = dref.getDataref("sim/custom/xap/firetest/apu")
    xac_firetest_e1 = dref.getDataref("sim/custom/xap/firetest/e1")
    xac_firetest_e2 = dref.getDataref("sim/custom/xap/firetest/e2")
    xac_APU_switch = dref.getDataref("sim/cockpit/engine/APU_switch")
    xac_apu_blvlv = dref.getDataref("sim/custom/xap/bleed/apu_blvlv")
    xac_bleed_mode_sw = dref.getDataref("sim/custom/xap/bleed/mode_sw")
    xac_start_pb = dref.getDataref("sim/custom/xap/apu/start_pb")
    xac_parbrake = dref.getDataref("sim/flightmodel/controls/parkbrake")
    xac_yellow_pump = dref.getDataref("sim/custom/xap/hydr/y/elpump/mode")
    xac_flap_ratio = dref.getDataref("sim/cockpit2/controls/flap_ratio")
    xac_speedbrake = dref.getDataref("sim/cockpit2/controls/speedbrake_ratio")
    xac_brake_auto_max = dref.getDataref("sim/custom/xap/brakes/auto_max")
    xac_rudder_trim = dref.getDataref("sim/cockpit2/controls/rudder_trim")
    xac_flap = dref.getDataref("sim/cockpit2/controls/flap_ratio")

    xac_window_heat = dref.getDataref("sim/cockpit2/ice/ice_window_heat_on")
    xac_pack1 = dref.getDataref("sim/custom/xap/cond/pack1")
    xac_pack2 = dref.getDataref("sim/custom/xap/cond/pack2")
    xac_temp_cock = dref.getDataref("sim/custom/xap/cond/ckpt_knob")
    xac_temp_fwd_cab = dref.getDataref("sim/custom/xap/cond/fwd_knob")
    xac_temp_aft_cab = dref.getDataref("sim/custom/xap/cond/aft_knob")

    -- adirs
    xac_adirs_data_sel = dref.getDataref("sim/custom/xap/adirs/data_sel")
    xac_adirs_sys_sel = dref.getDataref("sim/custom/xap/adirs/sys_sel")
    xac_adirs_mode_sel_1 = dref.getDataref("sim/custom/xap/adirs/mode_sel_1")
    xac_adirs_mode_sel_3 = dref.getDataref("sim/custom/xap/adirs/mode_sel_3")
    xac_adirs_mode_sel_2 = dref.getDataref("sim/custom/xap/adirs/mode_sel_2")
    xac_adirs_on_bat = dref.getDataref("sim/custom/xap/adirs/on_bat")
    xac_adirs_enter = dref.getDataref("sim/custom/xap/adirs/knob_ent")
    xac_adirs_disp = dref.getDataref("sim/custom/xap/adirs/disp")

    xac_emer_ext_lt = dref.getDataref("sim/custom/xap/extlight/emer_ext_lt")
    xac_alt_rot = dref.getDataref("sim/custom/xap/press/alt_rot")
    xac_radio_on = dref.getDataref("sim/custom/xap/radio/on")
    xac_fcu_fd = dref.getDataref("sim/custom/xap/fcu/fd")
    xac_fcu_ils = dref.getDataref("sim/custom/xap/fcu/ils")
    xac_atc_mode_sel = dref.getDataref("sim/custom/xap/atc/mode_sel")
    xac_atc_ta_tara = dref.getDataref("sim/custom/xap/atc/ta_tara")
    xac_ant_skeed = dref.getDataref("sim/custom/xap/wheels/ant_skeed")

    xac_efifs_waether = dref.getDataref("sim/cockpit/switches/EFIFS_shows_weather")

    xac_engn_thro = dref.getDataref("sim/flightmodel/engine/ENGN_thro")
    xac_throttle_ratio_all = dref.getDataref("sim/cockpit2/engine/actuators/throttle_ratio_all")

    xac_fasten_seat_belts = dref.getDataref("sim/cockpit/switches/fasten_seat_belts")
    xac_no_smoking = dref.getDataref("sim/cockpit2/switches/no_smoking")
    xac_beacon_sw = dref.getDataref("sim/custom/xap/extlight/beacon_sw")

    --groundservice

    xac_cater_on = dref.getDataref("sim/custom/xap/groundserv/cater/cat_on")
    xac_show_cater = dref.getDataref("sim/custom/xap/groundserv/cater/show_cater")
    xac_move_to_cater = dref.getDataref("sim/custom/xap/groundserv/cater/move_to_cater")

    xac_stair_on = dref.getDataref("sim/custom/xap/groundserv/stair/str_on")
    xac_show_stair = dref.getDataref("sim/custom/xap/groundserv/stair/show_stair")
    xac_move_to_stair = dref.getDataref("sim/custom/xap/groundserv/stair/move_to_stair")

    xac_tanker_on = dref.getDataref("sim/custom/xap/groundserv/tanker/tanker_on")
    xac_show_tanker = dref.getDataref("sim/custom/xap/groundserv/tanker/show_tanker")
    xac_load_on = dref.getDataref("sim/custom/xap/groundserv/load_on")
    xac_fm_on = dref.getDataref("sim/custom/xap/groundserv/gnd_fm_on")
    xac_tow_on = dref.getDataref("sim/custom/xap/groundserv/pwr_tow")
    xac_show_tow = dref.getDataref("sim/custom/xap/groundserv/show_tow")

    xac_chk_on = dref.getDataref("sim/custom/xap/groundserv/pwr_chk")

    --cover
    xac_chocks_l = dref.getDataref("sim/custom/xap/chocks_l")
    xac_chocks_r = dref.getDataref("sim/custom/xap/chocks_r")
    xac_cone = dref.getDataref("sim/custom/xap/cone")

    xac_cover_apu = dref.getDataref("sim/custom/xap/cover_apu")
    xac_cover_dn_pres_port_l = dref.getDataref("sim/custom/xap/cover_dn_pres_port_l")
    xac_cover_dn_pres_port_ll = dref.getDataref("sim/custom/xap/cover_dn_pres_port_ll")
    xac_cover_dn_pres_port_r = dref.getDataref("sim/custom/xap/cover_dn_pres_port_r")
    xac_cover_engine_l = dref.getDataref("sim/custom/xap/cover_engine_l")
    xac_cover_engine_r = dref.getDataref("sim/custom/xap/cover_engine_r")
    xac_cover_st_pres_port_lf = dref.getDataref("sim/custom/xap/cover_st_pres_port_lf")
    xac_cover_st_pres_port_lr = dref.getDataref("sim/custom/xap/cover_st_pres_port_lr")
    xac_cover_st_pres_port_rf = dref.getDataref("sim/custom/xap/cover_st_pres_port_rf")
    xac_cover_st_pres_port_rr = dref.getDataref("sim/custom/xap/cover_st_pres_port_rr")
    xac_nv_block_pin = dref.getDataref("sim/custom/xap/nv_block_pin")


    -- doors / menu
    xac_p_f_l_kn = dref.getDataref("sim/custom/xap/doors/p_f_l_kn")
    xac_p_f_r_kn = dref.getDataref("sim/custom/xap/doors/p_f_r_kn")
    xac_p_b_l_kn = dref.getDataref("sim/custom/xap/doors/p_b_l_kn")
    xac_p_b_r_kn = dref.getDataref("sim/custom/xap/doors/p_b_r_kn")
    xac_c_f_kn = dref.getDataref("sim/custom/xap/doors/c_f_kn")
    xac_c_b_kn = dref.getDataref("sim/custom/xap/doors/c_b_kn")

    -- doors / status
    xac_p_f_l_now = dref.getDataref("sim/custom/xap/doors/p_f_l_now")
    xac_p_f_r_now = dref.getDataref("sim/custom/xap/doors/p_f_r_now")
    xac_p_b_l_now = dref.getDataref("sim/custom/xap/doors/p_b_l_now")
    xac_p_b_r_now = dref.getDataref("sim/custom/xap/doors/p_b_r_now")
    xac_c_f_now = dref.getDataref("sim/custom/xap/doors/c_f_now")
    xac_c_b_now = dref.getDataref("sim/custom/xap/doors/c_b_now")

    -- mcdu
    xac_click_init = dref.getDataref("sim/custom/xap/mcdu/click_int")
    xac_click_perf = dref.getDataref("sim/custom/xap/mcdu/click_perf")
    xac_click_l1 = dref.getDataref("sim/custom/xap/mcdu/click_l1")
    xac_click_l2 = dref.getDataref("sim/custom/xap/mcdu/click_l2")
    xac_click_l3 = dref.getDataref("sim/custom/xap/mcdu/click_l3")
    xac_click_l4 = dref.getDataref("sim/custom/xap/mcdu/click_l4")
    xac_click_l5 = dref.getDataref("sim/custom/xap/mcdu/click_l5")
    xac_click_l6 = dref.getDataref("sim/custom/xap/mcdu/click_l6")
    xac_click_r1 = dref.getDataref("sim/custom/xap/mcdu/click_r1")
    xac_click_r2 = dref.getDataref("sim/custom/xap/mcdu/click_r2")
    xac_click_r3 = dref.getDataref("sim/custom/xap/mcdu/click_r3")
    xac_click_r4 = dref.getDataref("sim/custom/xap/mcdu/click_r4")
    xac_click_r5 = dref.getDataref("sim/custom/xap/mcdu/click_r5")
    xac_click_r6 = dref.getDataref("sim/custom/xap/mcdu/click_r6")
    xac_click_right = dref.getDataref("sim/custom/xap/mcdu/click_right")
    xac_click_clr = dref.getDataref("sim/custom/xap/mcdu/click_clr")
    xac_click_a = dref.getDataref("sim/custom/xap/mcdu/click_a")
    xac_click_b = dref.getDataref("sim/custom/xap/mcdu/click_b")
    xac_click_c = dref.getDataref("sim/custom/xap/mcdu/click_c")
    xac_click_d = dref.getDataref("sim/custom/xap/mcdu/click_d")
    xac_click_e = dref.getDataref("sim/custom/xap/mcdu/click_e")
    xac_click_f = dref.getDataref("sim/custom/xap/mcdu/click_f")
    xac_click_g = dref.getDataref("sim/custom/xap/mcdu/click_g")
    xac_click_h = dref.getDataref("sim/custom/xap/mcdu/click_h")
    xac_click_i = dref.getDataref("sim/custom/xap/mcdu/click_i")
    xac_click_j = dref.getDataref("sim/custom/xap/mcdu/click_j")
    xac_click_k = dref.getDataref("sim/custom/xap/mcdu/click_k")
    xac_click_l = dref.getDataref("sim/custom/xap/mcdu/click_l")
    xac_click_m = dref.getDataref("sim/custom/xap/mcdu/click_m")
    xac_click_n = dref.getDataref("sim/custom/xap/mcdu/click_n")
    xac_click_o = dref.getDataref("sim/custom/xap/mcdu/click_o")
    xac_click_p = dref.getDataref("sim/custom/xap/mcdu/click_p")
    xac_click_q = dref.getDataref("sim/custom/xap/mcdu/click_q")
    xac_click_r = dref.getDataref("sim/custom/xap/mcdu/click_r")
    xac_click_s = dref.getDataref("sim/custom/xap/mcdu/click_s")
    xac_click_t = dref.getDataref("sim/custom/xap/mcdu/click_t")
    xac_click_u = dref.getDataref("sim/custom/xap/mcdu/click_u")
    xac_click_v = dref.getDataref("sim/custom/xap/mcdu/click_v")
    xac_click_w = dref.getDataref("sim/custom/xap/mcdu/click_w")
    xac_click_x = dref.getDataref("sim/custom/xap/mcdu/click_x")
    xac_click_y = dref.getDataref("sim/custom/xap/mcdu/click_y")
    xac_click_z = dref.getDataref("sim/custom/xap/mcdu/click_z")
    xac_scratchpad = dref.getDataref("sim/custom/xap/mcdu/scratchpad")
    xac_line_3b = dref.getDataref("sim/custom/xap/mcdu/line_3b")
    xac_line_4b = dref.getDataref("sim/custom/xap/mcdu/line_4b")
    xac_line_2b = dref.getDataref("sim/custom/xap/mcdu/line_2b")
    xac_line_1b = dref.getDataref("sim/custom/xap/mcdu/line_1b")
    xac_line_2g = dref.getDataref("sim/custom/xap/mcdu/line_2g")
    xac_line_6g = dref.getDataref("sim/custom/xap/mcdu/line_6g")
    xac_line_5b = dref.getDataref("sim/custom/xap/mcdu/line_5b")
    xac_title_w = dref.getDataref("sim/custom/xap/mcdu/title_w")
    xac_arr_inhg = dref.getDataref("sim/custom/xap/mcdu/arr_inhg")
    xac_land_conf = dref.getDataref("sim/custom/xap/mcdu/land_conf")
    xac_temp_at_dest = dref.getDataref("sim/custom/xap/mcdu/temp_at_dest")
    xac_wind_dest_deg = dref.getDataref("sim/custom/xap/mcdu/wind_dest_deg")
    xac_wind_dest_knt = dref.getDataref("sim/custom/xap/mcdu/wind_dest_knt")
    xac_page_now = dref.getDataref("sim/custom/xap/mcdu/page_now")

    xac_flt_nbr = dref.getDataref("sim/custom/xap/mcdu/flt_nbr")
    xac_ci = dref.getDataref("sim/custom/xap/mcdu/ci")
    xac_alt_crzft = dref.getDataref("sim/custom/xap/ap/alt_crzft")

    -- fuel, start
    xac_block_fuel = dref.getDataref("sim/custom/xap/fuel/block_fuel")
    xac_extra_fuel = dref.getDataref("sim/custom/xap/fuel/extra_fuel")
    xac_final_fuel = dref.getDataref("sim/custom/xap/fuel/final_fuel")
    xac_rsv_fuel = dref.getDataref("sim/custom/xap/fuel/rsv_fuel")
    xac_taxi_fuel = dref.getDataref("sim/custom/xap/fuel/taxi_fuel")
    xac_trip_fuel = dref.getDataref("sim/custom/xap/fuel/trip_fuel")

    xac_t1_pump1 = dref.getDataref("sim/custom/xap/fuel/t1_pump1")
    xac_t1_pump2 = dref.getDataref("sim/custom/xap/fuel/t1_pump2")
    xac_t2_pump1 = dref.getDataref("sim/custom/xap/fuel/t2_pump1")
    xac_t2_pump2 = dref.getDataref("sim/custom/xap/fuel/t2_pump2")
    xac_t3_pump1 = dref.getDataref("sim/custom/xap/fuel/t3_pump1")
    xac_t3_pump2 = dref.getDataref("sim/custom/xap/fuel/t3_pump2")
    xac_startsel = dref.getDataref("sim/custom/xap/engines/startsel")
    xac_eng1msw = dref.getDataref("sim/custom/xap/engines/eng1msw")
    xac_eng2msw = dref.getDataref("sim/custom/xap/engines/eng2msw")
    xac_n2_percent = dref.getDataref("sim/cockpit2/engine/indicators/N2_percent")
    xac_fuel_quantity = dref.getDataref("sim/cockpit2/fuel/fuel_quantity")
    xac_t0 = dref.getDataref("sim/custom/xap/fuel/t0")
    xac_t1 = dref.getDataref("sim/custom/xap/fuel/t1")
    xac_t2 = dref.getDataref("sim/custom/xap/fuel/t2")
    xac_t3 = dref.getDataref("sim/custom/xap/fuel/t3")
    xac_t4 = dref.getDataref("sim/custom/xap/fuel/t4")


    -- temperature/ice/weather
    xac_outside_air_temp_degc = dref.getDataref("sim/cockpit2/temperature/outside_air_temp_degc")
    xac_ice_eng1_knob = dref.getDataref("sim/custom/xap/icerain/eng1_knob")
    xac_ice_eng2_knob = dref.getDataref("sim/custom/xap/icerain/eng2_knob")
    xac_ice_window = dref.getDataref("sim/custom/xap/icerain/window")
    xac_ice_wing_knob = dref.getDataref("sim/custom/xap/icerain/wing_knob")
    xac_wind_heading_deg_mag = dref.getDataref("sim/cockpit2/gauges/indicators/wind_heading_deg_mag")
    xac_wind_speed_kts = dref.getDataref("sim/cockpit2/gauges/indicators/wind_speed_kts")
    --sim/custom/xap/icerain/wing_knob_flt
    --sim/custom/xap/icerain/wip_l_anim
    --sim/custom/xap/icerain/wip_r_anim
    --sim/custom/xap/icerain/wiper_l
    --sim/custom/xap/icerain/wiper_r

    -- light
    xac_nose_sw = dref.getDataref("sim/custom/xap/extlight/nose_sw")
    xac_landr_sw = dref.getDataref("sim/custom/xap/extlight/landr_sw")
    xac_landl_sw = dref.getDataref("sim/custom/xap/extlight/landl_sw")
    xac_navlogo_sw = dref.getDataRef("sim/custom/xap/extlight/navlogo_sw")
    xac_strobe_sw = dref.getDataref("sim/custom/xap/extlight/strobe_sw")

    -- qnh
    xac_barometer_setting_in_hg_pilot = dref.getDataref("sim/cockpit2/gauges/actuators/barometer_setting_in_hg_pilot")
    xac_barometer_setting_in_hg_copilot = dref.getDataref("sim/cockpit2/gauges/actuators/barometer_setting_in_hg_copilot")
    xac_barometer_sealevel_inhg = dref.getDataref("sim/weather/barometer_sealevel_inhg")
    xac_barometer_setting = dref.getDataref("sim/cockpit/misc/barometer_setting")
    xac_barometer_setting2 = dref.getDataref("sim/cockpit/misc/barometer_setting2")
    --xac_ind_baro_hpa = dref.getDataref("sim/custom/xap/ind_baro_hpa")
    --xac_ind_baro_inhg = dref.getDataref("sim/custom/xap/ind_baro_inhg")

    xac_baro_flash = dref.getDataref("sim/custom/xap/pfd/baro_flash")

    -- fcu
    xac_push_baro = dref.getDataref("sim/custom/xap/fcu/push_baro")
    xac_ap1 = dref.getDataref("sim/custom/xap/fcu/ap1")
    xac_alt100x = dref.getDataref("sim/custom/xap/fcu/alt100x")
    --xac_alt1000x = dref.getDataref("sim/custom/xap/fcu/alt1000x") does not work ?
    xac_alt_pull_bat = dref.getDataref("sim/custom/xap/fcu/alt_pull_bat")
    xac_baro_ishpa = dref.getDataref("sim/custom/xap/fcu/baro_ishpa")

    -- altitude/alt
    xac_altitude_ft_pilot = dref.getDataref("sim/cockpit2/gauges/indicators/altitude_ft_pilot")
    xac_altitude = dref.getDataref("sim/cockpit/autopilot/altitude")
    xac_altitude_dial_ft = dref.getDataref("sim/cockpit2/autopilot/altitude_dial_ft")

    -- distance
    xac_gps_dme_dist_m = dref.getDataref("sim/cockpit/radios/gps_dme_dist_m")

    -- communication
    xac_transponder_code = dref.getDataref("sim/cockpit2/radios/actuators/transponder_code")
    xac_nav_com_adf_mode = dref.getDataref("sim/cockpit/radios/nav_com_adf_mode")
    xac_com1_freq_hz = dref.getDataref("sim/cockpit/radios/com1_freq_hz")
    xac_com2_freq_hz = dref.getDataref("sim/cockpit/radios/com2_freq_hz")
    xac_com1_stdby_freq_hz = dref.getDataref("sim/cockpit/radios/com1_stdby_freq_hz")
    xac_com2_stdby_freq_hz = dref.getDataref("sim/cockpit/radios/com2_stdby_freq_hz")

    --misc
    --xac_timer              = dref.getDataref("sim/cockpit2/clock_timer/local_time_seconds")

    -- approach
    xac_alt_dh_alt = dref.getDataref("sim/custom/xap/alt/dh_alt")
    xac_alt_mda_alt = dref.getDataref("sim/custom/xap/alt/mda_alt")
    xac_ap_trans_alt = dref.getDataref("sim/custom/xap/ap/trans_alt")
    xac_ap_trans_alt_star = dref.getDataref("sim/custom/xap/ap/trans_alt_star")


    -- own dataref
    xac_state_chk_box = dref.newIntArray("my/custom/dataref/state/chk_box")
    xac_state_preparation = dref.newIntArray("my/custom/dataref/state/preparation")
    xac_state_beforestart = dref.newIntArray("my/custom/dataref/state/beforestart")
    xac_state_start = dref.newIntArray("my/custom/dataref/state/start")
    xac_state_afterstart = dref.newIntArray("my/custom/dataref/state/afterstart")
    xac_state_taxi = dref.newIntArray("my/custom/dataref/state/taxi")
    xac_state_atholdingpoint = dref.newIntArray("my/custom/dataref/state/atholdingpoint")
    xac_state_linedup = dref.newIntArray("my/custom/dataref/state/linedup")
    xac_state_takeoff = dref.newIntArray("my/custom/dataref/state/takeoff")
    xac_state_descent = dref.newIntArray("my/custom/dataref/state/descent")

    xac_departure_transition = dref.newInt("my/custom/dataref/departure/transition")
    xac_daparture_station = dref.newInt("my/custom/dataref/departure/radio/station")
    xac_daparture_qnh_inHg = dref.newFloat("my/custom/dataref/departure/qnh_inHg")
    xac_daparture_info = dref.newByteArray("my/custom/dataref/departure/info")
    xac_daparture_apt = dref.newByteArray("my/custom/dataref/departure/apt")

    xac_approach_transition = dref.newInt("my/custom/dataref/approach/transition")
    xac_approach_goaround = dref.newInt("my/custom/dataref/approach/goaround")
    xac_approach_station = dref.newInt("my/custom/dataref/approach/radio/station")
    xac_approach_qnh_inHg = dref.newFloat("my/custom/dataref/approach/qnh_inHg")
    xac_approach_catII_III = dref.newInt("my/custom/dataref/approach/catII_III")
    xac_approach_info = dref.newByteArray("my/custom/dataref/approach/info")
    xac_approach_apt = dref.newByteArray("my/custom/dataref/approach/apt")

    xac_route_crzflinft = dref.newInt("my/custom/dataref/route/crzflinft")
    xac_route_fltnbr = dref.newByteArray("my/custom/dataref/route/fltnbr")

    xac_route_state = dref.newByteArray("my/custom/dataref/route/state")
    xac_route_info = dref.newByteArray("my/custom/dataref/route/info")
    xac_route_step = dref.newInt("my/custom/dataref/route/step")
    xac_route_dir = dref.newByteArray("my/custom/dataref/route/dir")
    xac_route_pointtype = dref.newByteArray("my/custom/dataref/route/pointtype")
    xac_route_routepart = dref.newByteArray("my/custom/dataref/route/routepart")
    xac_route_show_nom = dref.newInt("my/custom/dataref/route/show_nom")
    xac_route_next_act = dref.newInt("my/custom/dataref/route/next_act")
    xac_route_lat = dref.newFloat("my/custom/dataref/route/lat")
    xac_route_lon = dref.newFloat("my/custom/dataref/route/lon")
    xac_route_alt_min = dref.newInt("my/custom/dataref/route/alt_min")
    xac_route_alt_max = dref.newInt("my/custom/dataref/route/alt_max")
    xac_route_cst_min = dref.newInt("my/custom/dataref/route/cst_min")
    xac_route_cst_max = dref.newInt("my/custom/dataref/route/cst_max")
    xac_route_prof = dref.newFloat("my/custom/dataref/route/prof")
    xac_route_eutc = dref.newFloat("my/custom/dataref/route/eutc")
    xac_route_efob = dref.newFloat("my/custom/dataref/route/efob")
    xac_route_part = dref.newByteArray("my/custom/dataref/route/part")
    xac_route_dist = dref.newFloat("my/custom/dataref/route/dist")
    xac_route_brg = dref.newInt("my/custom/dataref/route/brg")
    xac_route_awy = dref.newByteArray("my/custom/dataref/route/awy")
    xac_route_freq = dref.newFloat("my/custom/dataref/route/freq")
    xac_route_crs = dref.newFloat("my/custom/dataref/route/crs")

    dref.setArraySize(xac_state_chk_box, 7)
    dref.setArraySize(xac_state_preparation, 7)
    dref.setArraySize(xac_state_beforestart, 7)
    dref.setArraySize(xac_state_start, 7)
    dref.setArraySize(xac_state_afterstart, 7)
    dref.setArraySize(xac_state_taxi, 7)
    dref.setArraySize(xac_state_atholdingpoint, 7)
    dref.setArraySize(xac_state_linedup, 7)
    dref.setArraySize(xac_state_takeoff, 7)
    dref.setArraySize(xac_state_descent, 7)
    dref.setArraySize(xac_daparture_info, 30)
    dref.setArraySize(xac_approach_info, 30)
    dref.setArraySize(xac_daparture_apt, 5)
    dref.setArraySize(xac_approach_apt, 5)
    dref.setArraySize(xac_route_state, 15)
    dref.setArraySize(xac_route_info, 30)
    dref.setArraySize(xac_route_dir, 10)
    dref.setArraySize(xac_route_pointtype, 10)
    dref.setArraySize(xac_route_routepart, 10)
    dref.setArraySize(xac_route_part, 10)
    dref.setArraySize(xac_route_awy, 10)
    dref.setArraySize(xac_route_fltnbr, 10)
    dref.setIntV(xac_state_chk_box, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_preparation, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_beforestart, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_start, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_afterstart, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_taxi, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_atholdingpoint, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_linedup, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_takeoff, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setIntV(xac_state_descent, 1, 0, 0, 0, 0, 0, 0, 0)
    dref.setString(xac_route_state, "DISPATCHING")
    dref.setString(xac_route_info, "NO FLIGHTPLAN FILED")
    dref.setString(xac_route_fltnbr, "---")
end